version: "3.9"

services:
  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
    environment:
      - FLASK_ENV=development
      - GEMINI_API_KEY=AIzaSyDpng7Ln7Goj8t96o4DxW7XoF72uhbwNkw
      - LINE_CHANNEL_ACCESS_TOKEN=m3Kw2lGKQay/V1OvhekHmVVkXYbpR8+BLWFenYTSP3CfbAAPUuvHJCghMU5ht2dlf4tgLFMC3tNiKZVsOSkU+P208hKXVpo5M4rLukPk486iLK2nCpeZkhnQMOzpywwzBMgeLEhD/Zc36XAWrzLDpgdB04t89/1O/w1cDnyilFU=
